version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  redis:
    image: redis
    ports:
      - '6378:6379'

  app:
    build: .
    env_file:
      .env

    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000

    ports:
      - '8001:8000'

    depends_on: [redis, db]

  celery:
    build: .
    env_file:
      - .env

    command: celery -A config worker -l DEBUG
    depends_on: [app]

  celery_beat:
    build: .
    env_file:
      - .env

    command: celery -A config beat -l info
    depends_on: [app]

volumes:
  pg_data: