# Generated by Django 4.2.6 on 2023-10-20 10:37

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='действие привычки')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.DateTimeField(verbose_name='время')),
                ('habit_type', models.CharField(choices=[('pleasant', 'приятная'), ('useful', 'полезная')], max_length=50, verbose_name='тип привычки')),
                ('periodicity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=7, validators=[django.core.validators.MaxLengthValidator(7), django.core.validators.MinLengthValidator(1)])),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='вознаграждение')),
                ('time_to_complete', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)], verbose_name='время выполнения (сек)')),
                ('publicity', models.CharField(choices=[('public', 'публичная'), ('private', 'приватная')], max_length=50, verbose_name='публичность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pleasant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_pleasants', to='main_app.habit')),
                ('useful', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_usefuls', to='main_app.habit')),
            ],
        ),
    ]
