# Generated by Django 4.2.6 on 2023-10-20 10:47

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=7, validators=[django.core.validators.MaxLengthValidator(7), django.core.validators.MinLengthValidator(1)], verbose_name='периодичность (в днях недели)'),
        ),
    ]
