# Generated by Django 4.2.6 on 2023-10-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
        migrations.AlterModelOptions(
            name='relatedhabits',
            options={'verbose_name': 'отношение привычки', 'verbose_name_plural': 'отношение привычек'},
        ),
    ]
