# Generated by Django 4.2.6 on 2023-10-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_habit_options_alter_relatedhabits_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedHabits',
            new_name='HabitsConnection',
        ),
        migrations.AlterModelOptions(
            name='habitsconnection',
            options={'verbose_name': 'связанная привычка', 'verbose_name_plural': 'связанные привычки'},
        ),
    ]
