# Generated by Django 4.2.6 on 2023-10-25 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_relatedhabits_habitsconnection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_time', models.DateTimeField(verbose_name='время отправки уведомления')),
                ('text', models.TextField(verbose_name='текст уведомления')),
                ('sending_type', models.CharField(choices=[('email', 'по почте'), ('telegram', 'в телеграм')], max_length=50, verbose_name='тип отправки')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main_app.habit')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
            },
        ),
    ]
